resources:
  - name: git-repo
    type: git
    icon: github
    source:
      uri: https://github.com/Rodhlann/react-with-concourse

jobs:
  - name: build-on-commit
    public: true
    plan:
      - get: git-repo
        trigger: true
      - task: build
        config:
          inputs:
            - name: git-repo
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: 14-alpine}
          run:
            path: yarn
            args: ["build"]